# Generated by Django 2.2.2 on 2019-06-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trans_id',
        ),
    ]
