# Generated by Django 2.2.2 on 2019-06-18 11:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_remove_transaction_trans_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
