# Generated by Django 2.2.2 on 2019-06-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_block'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='block',
            new_name='blocks',
        ),
    ]
