# Generated by Django 2.2.2 on 2019-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_auto_20190619_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocks',
            old_name='data',
            new_name='body',
        ),
        migrations.AddField(
            model_name='blocks',
            name='header',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
